# Generated by Django 2.0.1 on 2018-03-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingStatus',
            field=models.CharField(choices=[('ON_HOLD', 'ON_HOLD'), ('CONFIRMED', 'CONFIRMED'), ('CANCELLED', 'CANCELLED'), ('TRAVELLED', 'TRAVELLED')], default='ON_HOLD', max_length=10),
        ),
    ]
