# Generated by Django 2.0.3 on 2018-03-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_auto_20180319_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flightsArrivalDate',
            field=models.DateTimeField(),
        ),
    ]
