# Generated by Django 2.0.1 on 2018-03-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0003_auto_20180315_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproviders',
            name='accountPassword',
            field=models.CharField(default='', max_length=50),
        ),
    ]
