# Generated by Django 2.0.1 on 2018-05-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0003_auto_20180320_1133'),
        ('airlines', '0004_paymentproviders_accountpassword'),
    ]

    operations = [
    ]
