# Generated by Django 2.0.1 on 2018-05-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0005_merge_20180502_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentProviderName', models.CharField(max_length=100)),
                ('paymentAddress', models.URLField()),
                ('accountNumber', models.PositiveIntegerField(unique=True)),
                ('accountUsername', models.CharField(max_length=50, unique=True)),
                ('accountPassword', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Invoices',
            new_name='Invoice',
        ),
        migrations.DeleteModel(
            name='PaymentProviders',
        ),
    ]
