# Generated by Django 2.0.1 on 2018-05-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0006_auto_20180502_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='aircraftType',
            field=models.CharField(max_length=10),
        ),
    ]
